# Default configuration merged into sites using this theme as a Hugo module.

[markup]
  [markup.tableOfContents]
    startLevel = 2
    endLevel = 3
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true

[params]
  mainSections = ["posts"]

[outputs]
  home = ["HTML", "RSS", "JSON"]
